
const SUCCESS=200
const CREATED=201

const FORBIDDEN=403
const UNAUTHORIZED=401
const NOT_FOUND=404
const BAD_REQUEST=400
const INTERNAL_SERVER_ERROR=500

module.exports.SUCCESS=SUCCESS
module.exports.CREATED=CREATED
module.exports.NOT_FOUND=NOT_FOUND
module.exports.BAD_REQUEST=BAD_REQUEST
module.exports.INTERNAL_SERVER_ERROR=INTERNAL_SERVER_ERROR
module.exports.UNAUTHORIZED=UNAUTHORIZED
module.exports.FORBIDDEN=FORBIDDEN
